/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : bigint,
  'metadata' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'eventType' : ActivityEventType,
}
export type ActivityEventType = { 'Login' : null } |
  { 'FailedLogin' : null } |
  { 'ProfileUpdate' : null } |
  { 'MarketplaceClick' : null } |
  { 'CropDoctorUpload' : null } |
  { 'IrrigationToggle' : null } |
  { 'BestPriceSearch' : null };
export interface ActivityFilter {
  'startTime' : [] | [bigint],
  'endTime' : [] | [bigint],
  'eventType' : [] | [ActivityEventType],
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'isAdmin' : boolean,
}
export interface _SERVICE {
  'getActivityLog' : ActorMethod<[ActivityFilter], Array<ActivityEntry>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<[ActivityEventType, string], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], boolean>,
  'removeAdmin' : ActorMethod<[Principal], boolean>,
  'updateUserProfile' : ActorMethod<[string, string], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];