/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityEventType = IDL.Variant({
  'Login' : IDL.Null,
  'FailedLogin' : IDL.Null,
  'ProfileUpdate' : IDL.Null,
  'MarketplaceClick' : IDL.Null,
  'CropDoctorUpload' : IDL.Null,
  'IrrigationToggle' : IDL.Null,
  'BestPriceSearch' : IDL.Null,
});
export const ActivityFilter = IDL.Record({
  'startTime' : IDL.Opt(IDL.Int),
  'endTime' : IDL.Opt(IDL.Int),
  'eventType' : IDL.Opt(ActivityEventType),
});
export const ActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'metadata' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'eventType' : ActivityEventType,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'isAdmin' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getActivityLog' : IDL.Func(
      [ActivityFilter],
      [IDL.Vec(ActivityEntry)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([ActivityEventType, IDL.Text], [], []),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityEventType = IDL.Variant({
    'Login' : IDL.Null,
    'FailedLogin' : IDL.Null,
    'ProfileUpdate' : IDL.Null,
    'MarketplaceClick' : IDL.Null,
    'CropDoctorUpload' : IDL.Null,
    'IrrigationToggle' : IDL.Null,
    'BestPriceSearch' : IDL.Null,
  });
  const ActivityFilter = IDL.Record({
    'startTime' : IDL.Opt(IDL.Int),
    'endTime' : IDL.Opt(IDL.Int),
    'eventType' : IDL.Opt(ActivityEventType),
  });
  const ActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'metadata' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'eventType' : ActivityEventType,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  
  return IDL.Service({
    'getActivityLog' : IDL.Func(
        [ActivityFilter],
        [IDL.Vec(ActivityEntry)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([ActivityEventType, IDL.Text], [], []),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };