/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityEntry {
    id: bigint;
    metadata: string;
    userId: Principal;
    timestamp: bigint;
    eventType: ActivityEventType;
}
export interface ActivityFilter {
    startTime?: bigint;
    endTime?: bigint;
    eventType?: ActivityEventType;
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    createdAt: bigint;
    fullName: string;
    isAdmin: boolean;
}
export enum ActivityEventType {
    Login = "Login",
    FailedLogin = "FailedLogin",
    ProfileUpdate = "ProfileUpdate",
    MarketplaceClick = "MarketplaceClick",
    CropDoctorUpload = "CropDoctorUpload",
    IrrigationToggle = "IrrigationToggle",
    BestPriceSearch = "BestPriceSearch"
}
export interface backendInterface {
    getActivityLog(filter: ActivityFilter): Promise<Array<ActivityEntry>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getUserProfile(): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    logActivity(eventType: ActivityEventType, metadata: string): Promise<void>;
    promoteToAdmin(target: Principal): Promise<boolean>;
    removeAdmin(target: Principal): Promise<boolean>;
    updateUserProfile(displayName: string, fullName: string): Promise<UserProfile>;
}
import type { ActivityEntry as _ActivityEntry, ActivityEventType as _ActivityEventType, ActivityFilter as _ActivityFilter, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getActivityLog(arg0: ActivityFilter): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog(to_candid_ActivityFilter_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog(to_candid_ActivityFilter_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async logActivity(arg0: ActivityEventType, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(to_candid_ActivityEventType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(to_candid_ActivityEventType_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async promoteToAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdmin(arg0);
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActivityEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): ActivityEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityEventType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEventType): ActivityEventType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    metadata: string;
    userId: Principal;
    timestamp: bigint;
    eventType: _ActivityEventType;
}): {
    id: bigint;
    metadata: string;
    userId: Principal;
    timestamp: bigint;
    eventType: ActivityEventType;
} {
    return {
        id: value.id,
        metadata: value.metadata,
        userId: value.userId,
        timestamp: value.timestamp,
        eventType: from_candid_ActivityEventType_n8(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Login: null;
} | {
    FailedLogin: null;
} | {
    ProfileUpdate: null;
} | {
    MarketplaceClick: null;
} | {
    CropDoctorUpload: null;
} | {
    IrrigationToggle: null;
} | {
    BestPriceSearch: null;
}): ActivityEventType {
    return "Login" in value ? ActivityEventType.Login : "FailedLogin" in value ? ActivityEventType.FailedLogin : "ProfileUpdate" in value ? ActivityEventType.ProfileUpdate : "MarketplaceClick" in value ? ActivityEventType.MarketplaceClick : "CropDoctorUpload" in value ? ActivityEventType.CropDoctorUpload : "IrrigationToggle" in value ? ActivityEventType.IrrigationToggle : "BestPriceSearch" in value ? ActivityEventType.BestPriceSearch : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Array<ActivityEntry> {
    return value.map((x)=>from_candid_ActivityEntry_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityEventType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): _ActivityEventType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityFilter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityFilter): _ActivityFilter {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: bigint;
    endTime?: bigint;
    eventType?: ActivityEventType;
}): {
    startTime: [] | [bigint];
    endTime: [] | [bigint];
    eventType: [] | [_ActivityEventType];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        eventType: value.eventType ? candid_some(to_candid_ActivityEventType_n3(_uploadFile, _downloadFile, value.eventType)) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): {
    Login: null;
} | {
    FailedLogin: null;
} | {
    ProfileUpdate: null;
} | {
    MarketplaceClick: null;
} | {
    CropDoctorUpload: null;
} | {
    IrrigationToggle: null;
} | {
    BestPriceSearch: null;
} {
    return value == ActivityEventType.Login ? {
        Login: null
    } : value == ActivityEventType.FailedLogin ? {
        FailedLogin: null
    } : value == ActivityEventType.ProfileUpdate ? {
        ProfileUpdate: null
    } : value == ActivityEventType.MarketplaceClick ? {
        MarketplaceClick: null
    } : value == ActivityEventType.CropDoctorUpload ? {
        CropDoctorUpload: null
    } : value == ActivityEventType.IrrigationToggle ? {
        IrrigationToggle: null
    } : value == ActivityEventType.BestPriceSearch ? {
        BestPriceSearch: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
